travis:
  secure:
    BINSTAR_TOKEN: irjq1MEaHDOzojTBhusaq5BLOYjhEyJWwXGXL6V6R7j0xYRdnASALX3bBIPaN8Uob3mWnsXOGfBTq4MCaAw9r24O6Va25QlRzMgDArV31qw+mSF5MRnfH5juFJ/Q8hpFZHZs+zcXhPxENCeL9M/EbrPbCrxM71fIf5SHRkC5MKnSWH2y5Ie0DaIoxsxBB78uPa3fH8AYW/GBDA5mg9D5ysJvmnkpCl2j5Pg/22uzY5aFnLT8Kyk5NmFlhL0zKlU+kt+NYNHt1Py3xGWe0KQwQunWc11EivDD546o1iXshqafcbB1Xi48ODu39jFStXS0pytyP9K8ENABQpWDQrd+jAJ+iAoK0R/OuqrKk52ESSI1dSDDOaKH4AjmuvgbCrsC6KdnbVzzuq0tnCXAlRu3q/rT6EaSq6E5+eyzGs+G2+MS9vI/b8wXG9ANw/Hyulj9uvg/44yJuM64CNGP5DhpnuOj+L4Fbp3GUAIGUAUMAvY0CmGQvTtWmQHH4fw0Bv/t9vngGP7daX9Fao5wKZFcznwqVILFdQJShIAgYFIZhAREfTS8MIuGHtXKsQNdaHU6a1uDY90R1t4k4BBWHHN+0ItKED6YZqjX5bISAGTRYSGc6D6BZGRDSmhGen6Wbuy0KMwlV3Q1rjKjPKURx3WE9qdKwMULOdDQKe2mBSAhy7k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
